NO_TEAM = 0
RED_TEAM = 1
BLUE_TEAM = 2

NO_FLAG = 0
OPP_FLAG = 1
OPP_POTATO_FLAG = 2
NEUTRAL_FLAG = 3
NEUTRAL_POTATO_FLAG = 4
TEMP_FLAG = 5

NO_POWER = 0
JUKE_JUICE = 1
ROLLING_BOMB = 2
TAGPRO = 4
TOP_SPEED = 8

POWERUPS = (JUKE_JUICE, ROLLING_BOMB, TAGPRO, TOP_SPEED)
