# Teams
NO_TEAM = 0
RED_TEAM = 1
BLUE_TEAM = 2

# Flags
NO_FLAG = 0
OPP_FLAG = 1
OPP_POTATO_FLAG = 2
NEUTRAL_FLAG = 3
NEUTRAL_POTATO_FLAG = 4
TEMP_FLAG = 5

# Powerups
NO_POWER = 0
JUKE_JUICE = 1
ROLLING_BOMB = 2
TAGPRO = 4
TOP_SPEED = 8

POWERUPS = (JUKE_JUICE, ROLLING_BOMB, TAGPRO, TOP_SPEED)

# Tiles
EMPTY_TILE = 0

FULL_WALL_TILE = 10
LL_WALL_TILE = 11
UL_WALL_TILE = 12
UR_WALL_TILE = 13
LR_WALL_TILE = 14

FLOOR_TILE = 20

RED_TEAM_TILE = 110
BLUE_TEAM_TILE = 120
NEUTRAL_TEAM_TILE = 230

RED_FLAG_TILE = 30
BLUE_FLAG_TILE = 40
NEUTRAL_FLAG_TILE = 160

RED_POTATO_TILE = 190
BLUE_POTATO_TILE = 200
NEUTRAL_POTATO_TILE = 210

TEMP_FLAG_TILE = 161

NEUTRAL_BOOST_TILE = 50
RED_BOOST_TILE = 140
BLUE_BOOST_TILE = 150

BOMB_TILE = 100

SPIKE_TILE = 70

POWERUP_TILE = 60
JUKE_JUICE_TILE = 61
ROLLING_BOMB_TILE = 62
TAGPRO_TILE = 63
TOP_SPEED_TILE = 64

BUTTON_TILE = 80

OPEN_GATE_TILE = 90
GREEN_GATE_TILE = 91
RED_GATE_TILE = 92
BLUE_GATE_TILE = 93

PORTAL_ENTRY_TILE = 130
PORTAL_EXIT_TILE = 131

RED_ENDZONE_TILE = 170
BLUE_ENDZONE_TILE = 180

MARSBALL_TILE = 211

GRAVITY_WELL_TILE = 220
